In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib import patches
import numpy as np

In [136]:
##########Here we define a cost function for calculating inital cost/loss of the dataset ##########
def Compute_Cost(X,y,theta):
    m=len(y)
    k=1/(2*m)
    sqrerrors=np.square(np.matmul(X,theta)-y)
    J=k*sum(sqrerrors)
    return J

In [137]:
######this function is for calculating theta/paramter that fit the dataset by using gradient descent#######
def Gradient_descent(X,y,theta,alpha,num_iter):
    m=len(y)
    a,b=X.shape
    for i in range(num_iter):
        for j in range(b):
            x=X[:,j]
            x=x[:,np.newaxis]
            pk=sum((np.matmul(X,theta)-y)*(x))
            theta[j]=theta[j]-(alpha*(1/m)*pk)
        #print(Compute_Cost(X,y,theta))
    return theta

In [138]:
# read the csv file using read_csv function of pandas
df = pd.read_csv(r"C:\Users\SRAVAN NEELI\Desktop\DAIICT\DeepLearning\Assignment 1\problem-statement-data\data_carsmall.csv")
df.head()

x1         x2            x3          x4      x5     y
0  Acceleration  Cylinders  Displacement  Horsepower  Weight   MPG
1          12.0        8.0         307.0       130.0  3504.0  18.0
2          11.5        8.0         350.0       165.0  3693.0  15.0
3          11.0        8.0         318.0       150.0  3436.0  18.0
4          12.0        8.0         304.0       150.0  3433.0  16.0

In [139]:
########cleaning the dataset which are with Nan format ######################
p,q=df.shape
train=df[df.y.notna()]
test=df[df.y.isna()]
train=train.fillna(0)
train.head()


x1         x2            x3          x4      x5     y
0  Acceleration  Cylinders  Displacement  Horsepower  Weight   MPG
1          12.0        8.0         307.0       130.0  3504.0  18.0
2          11.5        8.0         350.0       165.0  3693.0  15.0
3          11.0        8.0         318.0       150.0  3436.0  18.0
4          12.0        8.0         304.0       150.0  3433.0  16.0

In [140]:
###################Here we are splitting dataset to train and test dataset#########################
X_train=train.iloc[1:,0:q-1]
y_train=train.iloc[1:,q-1:q]
X_test=test.iloc[0:,0:q-1]
y_test=test.iloc[0:,q-1:q]
X_train=X_train.fillna(0)
##########converting dataframes to arrays###########
X_train=X_train.astype(float).values
y_train=y_train.astype(float).values
X_test=X_test.astype(float).values
#########normalization#############################
X_train=(X_train-X_train.mean())/X_train.std()
X_test=(X_test-X_test.mean())/X_test.std()

In [141]:
######initalizing values for theta###########
theta=np.zeros((np.size(X_train[0,:])+1,1))

In [142]:
X=X_train
y=y_train
a,b=X.shape
ones=np.ones((a,1))
##########appending bias column to training data###########
X=np.append(ones,X,axis=1)


In [143]:
######calling cost function##########
J=Compute_Cost(X,y,theta)
print(J)

[313.21675532]


In [144]:
########initalizig suitalbe values for running gradient descent################
alpha=0.3
num_iter=1000
np.shape(theta)
theta=Gradient_descent(X,y,theta,alpha,num_iter)

In [145]:
######## trained wieghts/parameters which can be used for test data################
print(theta)

[[ 22.76570399]
 [ -8.28465677]
 [ -8.11819381]
 [-11.282929  ]
 [ -9.44408044]
 [ -8.60776886]]


In [146]:
#########pre-processing of test-data##############
y_test=y_test.fillna(0)
k,q=X_test.shape
prediction={}
ones=np.ones((k,1))
X_test=np.append(ones,X_test,axis=1)

In [147]:
####prediction for the test data#########
for i in range(k):
    y_test.iloc[i,0]=np.matmul(X_test[i,:],theta)

In [148]:
print(y_test)#predicting the values for test data

            y
11  29.261411
12  21.162794
13  21.864270
14  20.712394
15  22.727388
18  26.308402


In [149]:
######################POLYNOMIAL REGRESSION TO FIT THE DATA MORE ACCURATELY#####################
######################HERE WE USE SKLEARN LIBRARY TO TRAIN THE DATA AND TEST IT ################
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [150]:
df = pd.read_csv(r"C:\Users\SRAVAN NEELI\Desktop\DAIICT\DeepLearning\Assignment 1\problem-statement-data\data_carsmall.csv")
df.head()

x1         x2            x3          x4      x5     y
0  Acceleration  Cylinders  Displacement  Horsepower  Weight   MPG
1          12.0        8.0         307.0       130.0  3504.0  18.0
2          11.5        8.0         350.0       165.0  3693.0  15.0
3          11.0        8.0         318.0       150.0  3436.0  18.0
4          12.0        8.0         304.0       150.0  3433.0  16.0

In [151]:
#########splitting data into train and test data###########
p,q=df.shape
train=df[df.y.notna()]
test=df[df.y.isna()]
train=train.fillna(0)
train.head()

x1         x2            x3          x4      x5     y
0  Acceleration  Cylinders  Displacement  Horsepower  Weight   MPG
1          12.0        8.0         307.0       130.0  3504.0  18.0
2          11.5        8.0         350.0       165.0  3693.0  15.0
3          11.0        8.0         318.0       150.0  3436.0  18.0
4          12.0        8.0         304.0       150.0  3433.0  16.0

In [152]:
######### spliting data for train data input and target data ######################
X_train=train.iloc[1:,0:q-1]
y_train=train.iloc[1:,q-1:q]
X_test=test.iloc[0:,0:q-1]
y_test=test.iloc[0:,q-1:q]
X_train=X_train.fillna(0)
################### converting data to numpy arrays ##############################
X_train=X_train.astype(float).values
y_train=y_train.astype(float).values
X_test=X_test.astype(float).values

In [153]:
##############transforming data to into polynomial regression #################
poly=PolynomialFeatures(degree=2)
regressor=LinearRegression()

In [154]:
poly_X=poly.fit_transform(X_train)

In [155]:
########fitting the generated polynomial dataset ####################
regressor.fit(poly_X,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [156]:
########### Getting the parameters/wieghts of the trained model #############
regressor.coef_

array([[ 0.00000000e+00, -2.26667234e-01,  1.11690750e+00,
        -3.20346471e-02, -3.62791078e-01, -4.93586799e-03,
         6.04036595e-02, -9.93488594e-01,  1.78635994e-02,
         3.46660561e-03, -1.12438768e-04, -1.12040653e+00,
        -4.35682697e-02, -1.29889664e-02,  1.11959092e-02,
         5.61802835e-04,  9.37844487e-04, -9.57500135e-05,
        -1.18544094e-03,  1.13437569e-04, -8.68226250e-06]])

In [157]:
################# transforming test data ###############
poly_X_test=poly.fit_transform(X_test)

In [158]:
############predicting the test data ##################
regressor.predict(poly_X_test)

array([[18.74244356],
       [15.21807475],
       [15.90757205],
       [14.76908216],
       [15.11349483],
       [19.63610222]])